apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-thqc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-thqc
    app.kubernetes.io/part-of: tkwch-fix-0075-0042-app
  name: devfile-sample-thqc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-thqc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-thqc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-21-tenant/tkwch-fix-0075-0042-app/devfile-sample-thqc@sha256:6ce69384b2211a96ba8beddd0e28ea0fc6e49a993ced2facb017304f5084f25f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
